## This YML file used to serve as a config file for MyBinder deployment and is not currently in use.

name: proganalytics-environment
channels:
  - conda-forge
dependencies:
  - pandas
  - matplotlib
  - numpy
  - scipy
  - ipywidgets
  - plotly
  - importlib
